const dbSite=supabase.createClient(DCY_CONFIG.SUPABASE_URL,DCY_CONFIG.SUPABASE_KEY),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),NL=s=>E(s).replace(/\n/g,'<br>'),ST=n=>'★'.repeat(+n||0)+'☆'.repeat(5-(+n||0));let SV=[],MT=[],PJ=[],AR=[],FQ=[];
(async()=>{const [a,s,m,p,d,c,ar,fq]=await Promise.all([dbSite.from('about_content').select('*').eq('id',1).maybeSingle(),dbSite.from('services').select('*').eq('active',true).order('sort_order'),dbSite.from('materials').select('*').eq('active',true).order('category').order('sort_order'),dbSite.from('projects').select('*').eq('published',true).order('featured',{ascending:false}).order('sort_order'),dbSite.from('dm_files').select('*').eq('id',1).maybeSingle(),dbSite.from('site_settings').select('*').eq('id',1).maybeSingle(),dbSite.from('articles').select('*').eq('published',true).order('published_at',{ascending:false}).order('sort_order'),dbSite.from('faqs').select('*').eq('active',true).order('sort_order')]);let A=a.data||{},C=c.data||{};SV=s.data||[];MT=m.data||[];PJ=p.data||[];AR=ar.data||[];FQ=fq.data||[];aboutTitle.textContent=A.title||'關於我們';aboutSummary.textContent=A.summary||'專注於 3D 列印、產品打樣與設計開發服務。';aboutContent.innerHTML=NL(A.content||'');aboutPhilosophy.innerHTML=A.philosophy?`<b>經營理念</b><br>${NL(A.philosophy)}`:'';renderServices();renderMaterialTabs();renderMaterials();renderProjects();renderArticles();renderFaq();renderQuoteMaterials();if(d.data?.file_url){dmLink.hidden=false;dmLink.href=d.data.file_url;dmLink.textContent=d.data.title||'查看／下載公司 DM'}renderContact(C);renderBrand(C);renderHome(C);renderSEO(C)})();
function renderServices(){serviceGrid.innerHTML=SV.map((x,i)=>`<article class="card visual-card" onclick="openService('${x.id}')">${x.image_url?`<img src="${E(x.image_url)}" alt="${E(x.name)}">`:''}<div><span class="num">SERVICE ${String(i+1).padStart(2,'0')}</span><h3>${E(x.name)}</h3><p>${E(x.description||'')}</p><span class="more">了解更多 →</span></div></article>`).join('')}
function renderMaterialTabs(){let cats=['全部',...new Set(MT.map(x=>x.category))];materialTabs.innerHTML=cats.map((c,i)=>`<button class="${i?'':'active'}" onclick="filterMaterials(this,'${E(c)}')">${E(c)}</button>`).join('')};window.filterMaterials=(b,c)=>{[...materialTabs.children].forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMaterials(c)};
function renderMaterials(cat='全部'){let a=cat==='全部'?MT:MT.filter(x=>x.category===cat);materialGrid.innerHTML=a.map(x=>`<article class="card visual-card" onclick="openMaterial('${x.id}')">${x.image_url?`<img src="${E(x.image_url)}" alt="${E(x.name)}">`:''}<div><span class="num">${E(x.category)}</span><h3>${E(x.name)}</h3><p>${E(x.summary||'點選查看材料特性、適用範圍與製作範例。')}</p><span class="more">查看材料 →</span></div></article>`).join('')}
function renderProjects(){projectGrid.innerHTML=PJ.length?PJ.map(x=>`<article class="project" onclick="openProject('${x.id}')">${x.cover_url?`<img src="${E(x.cover_url)}" alt="${E(x.title)}">`:`<div class="placeholder">DCY<br>PROJECT</div>`}<div class="body"><small>${E(x.industry|| (x.featured?'FEATURED':'PROJECT'))}</small><h3>${E(x.title)}</h3><p>${E(x.summary||'')}</p></div></article>`).join(''):'<p>案例整理中，後續將持續更新。</p>'}
function renderArticles(){articleGrid.innerHTML=AR.length?AR.slice(0,6).map(x=>`<article class="article" onclick="openArticle('${x.id}')">${x.cover_url?`<img src="${E(x.cover_url)}">`:'<div class="article-ph">DCY</div>'}<div><small>${E(x.category)}｜${E(x.published_at||'')}</small><h3>${E(x.title)}</h3><p>${E(x.summary||'')}</p></div></article>`).join(''):'<p>技術文章準備中。</p>'}
function renderFaq(){faqList.innerHTML=FQ.length?FQ.map(x=>`<details><summary><span>${E(x.question)}</span><b>＋</b></summary><p>${NL(x.answer)}</p></details>`).join(''):'<p>常見問題整理中。</p>'}
function renderQuoteMaterials(){qMaterial.innerHTML='<option value="">未指定／請協助評估</option>'+MT.map(x=>`<option value="${x.id}">${E(x.name)}</option>`).join('')}
function modalOpen(h){modalBody.innerHTML=h;modal.hidden=false;document.body.style.overflow='hidden'}modalClose.onclick=()=>{modal.hidden=true;document.body.style.overflow=''};modal.onclick=e=>{if(e.target===modal)modalClose.click()};
function relatedProjects(k,v){return PJ.filter(x=>x[k]===v).slice(0,4).map(x=>`<button class="related-card" onclick="openProject('${x.id}')">${x.cover_url?`<img src="${E(x.cover_url)}">`:''}<span>${E(x.title)}</span></button>`).join('')}
function openService(id){let x=SV.find(v=>v.id===id);if(!x)return;modalOpen(`<p class="eyebrow">SERVICE</p><h2>${E(x.name)}</h2>${x.image_url?`<img class="detail-img" src="${E(x.image_url)}">`:''}<p>${NL(x.full_content||x.description||'')}</p>${x.applications?`<h3>適合應用</h3><p>${NL(x.applications)}</p>`:''}<h3>相關案例</h3><div class="related-grid">${relatedProjects('service_id',id)||'<p>案例整理中。</p>'}</div><a class="btn" href="#quote" onclick="modalClose.click()">取得報價</a>`)}
function openMaterial(id){let x=MT.find(v=>v.id===id);if(!x)return;let examples=x.example_urls||[];modalOpen(`<p class="eyebrow">${E(x.category)}</p><h2>${E(x.name)}</h2>${x.image_url?`<img class="detail-img" src="${E(x.image_url)}">`:''}<p>${NL(x.full_content||x.summary||'')}</p><div class="ratings"><span>強度 ${ST(x.strength)}</span><span>韌性 ${ST(x.toughness)}</span><span>耐熱 ${ST(x.heat_resistance)}</span><span>表面 ${ST(x.surface_quality)}</span></div>${x.colors?`<h3>可提供顏色</h3><p>${NL(x.colors)}</p>`:''}${x.features?`<h3>材料特色</h3><p>${NL(x.features)}</p>`:''}${x.applications?`<h3>適合用途</h3><p>${NL(x.applications)}</p>`:''}${x.cautions?`<h3>注意事項</h3><p>${NL(x.cautions)}</p>`:''}<h3>${E(x.name)} 製作範例</h3><div class="gallery">${examples.length?examples.map(u=>`<img src="${E(u)}">`).join(''):'<p>範例照片準備中。</p>'}</div><h3>使用此材料的案例</h3><div class="related-grid">${relatedProjects('material_id',id)||'<p>案例整理中。</p>'}</div><a class="btn" href="#quote" onclick="modalClose.click();qMaterial.value='${id}'">詢問此材料</a>`)}
function openProject(id){let x=PJ.find(v=>v.id===id),s=SV.find(v=>v.id===x?.service_id),m=MT.find(v=>v.id===x?.material_id);if(!x)return;modalOpen(`<p class="eyebrow">PROJECT</p><h2>${E(x.title)}</h2>${!x.hide_client&&x.client_name?`<p><b>客戶：</b>${E(x.client_name)}</p>`:''}<p>${x.industry?`<b>產業：</b>${E(x.industry)}　`:''}${s?`<b>服務：</b>${E(s.name)}　`:''}${m?`<b>材料：</b>${E(m.name)}`:''}</p>${x.cover_url?`<img class="detail-img" src="${E(x.cover_url)}">`:''}<p>${NL(x.content||x.summary||'')}</p>${x.production_notes?`<h3>製作重點</h3><p>${NL(x.production_notes)}</p>`:''}<div class="gallery">${(x.gallery_urls||[]).map(u=>`<img src="${E(u)}">`).join('')}</div>`)}
function openArticle(id){let x=AR.find(v=>v.id===id);if(x)modalOpen(`<p class="eyebrow">${E(x.category)}</p><h2>${E(x.title)}</h2><p class="muted">${E(x.published_at||'')}</p>${x.cover_url?`<img class="detail-img" src="${E(x.cover_url)}">`:''}<p>${NL(x.content||x.summary||'')}</p>`)}
function renderContact(s){let a=[];if(s.show_email&&s.email)a.push(['EMAIL',`mailto:${s.email}`,s.email]);if(s.show_line&&s.line_url)a.push(['LINE',s.line_url,'LINE 聯絡']);if(s.show_phone&&s.phone)a.push(['TEL',`tel:${s.phone}`,s.phone]);if(s.show_instagram&&s.instagram_url)a.push(['INSTAGRAM',s.instagram_url,'Instagram']);if(s.show_facebook&&s.facebook_url)a.push(['FACEBOOK',s.facebook_url,'Facebook']);if(s.show_address&&s.address)a.push(['ADDRESS','',s.address]);contactGrid.innerHTML=a.map(([l,u,t])=>u?`<a href="${E(u)}" ${u.startsWith('http')?'target="_blank" rel="noopener"':''}><small>${l}</small><b>${E(t)}</b></a>`:`<div><small>${l}</small><b>${E(t)}</b></div>`).join('')}
function renderBrand(s){if(s.logo_url)brandLogo.src=s.logo_url;if(s.logo_width)brandLogo.style.width=`${Math.max(50,Math.min(180,+s.logo_width))}px`;let bn=s.company_name||'鼎程溢企業社',be=s.company_name_en||'DING CHENG YI ENTERPRISE';brandName.textContent=footerBrandName.textContent=bn;brandNameEn.textContent=footerBrandNameEn.textContent=be;brandText.style.display=s.show_brand_text===false?'none':'flex';if(s.favicon_url){let l=document.querySelector("link[rel='icon']")||document.head.appendChild(document.createElement('link'));l.rel='icon';l.href=s.favicon_url}}
function renderHome(s){let t=s.hero_title||'從想法，到實際製作。',parts=t.split('，');heroTitle.innerHTML=parts.length>1?`${E(parts[0])}，<br><span>${E(parts.slice(1).join('，'))}</span>`:E(t);heroSubtitle.textContent=s.hero_subtitle||'';heroDescription.textContent=s.hero_description||'';heroQuoteBtn.textContent=s.quote_button_text||'取得報價';if(s.hero_image_url){heroImage.src=s.hero_image_url;heroImage.hidden=false;heroVisual.classList.add('has-image')}}
function renderSEO(s){document.title=s.seo_title||document.title;metaDescription.content=s.seo_description||metaDescription.content;metaKeywords.content=s.seo_keywords||'';ogTitle.content=s.seo_title||document.title;ogDescription.content=s.seo_description||'';if(s.share_image_url)ogImage.content=s.share_image_url}
qFiles.onchange=()=>qFileNames.textContent=[...qFiles.files].map(f=>f.name).join('、');async function uploadQuoteFile(file){let ext=file.name.split('.').pop(),path=`${Date.now()}-${crypto.randomUUID()}.${ext}`,r=await dbSite.storage.from('inquiry-files').upload(path,file);if(r.error)throw r.error;return path}
quoteForm.onsubmit=async e=>{e.preventDefault();quoteMsg.textContent='送出中…';try{let files=[...qFiles.files].slice(0,5),urls=[];for(let f of files)urls.push(await uploadQuoteFile(f));let no=`DCY-Q-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(Date.now()).slice(-4)}`,p={inquiry_no:no,customer_name:qName.value,company_name:qCompany.value,email:qEmail.value,phone:qPhone.value,line_id:qLine.value,request_type:qType.value,material_id:qMaterial.value||null,quantity:qQty.value,dimensions:qDimensions.value,purpose:qPurpose.value,desired_date:qDate.value||null,description:qDescription.value,file_urls:urls,status:'new'};let {error}=await dbSite.from('inquiries').insert(p);if(error)throw error;quoteForm.reset();qFileNames.textContent='';quoteMsg.textContent=`✓ 詢價已送出，案件編號：${no}`}catch(err){quoteMsg.textContent='送出失敗：'+err.message}}
