const db=supabase.createClient(DCY_CONFIG.SUPABASE_URL,DCY_CONFIG.SUPABASE_KEY);
const $=id=>document.getElementById(id);let services=[],materials=[],projects=[];
async function boot(){const {data:{session}}=await db.auth.getSession();if(session)showApp(session.user)}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginMsg").textContent="登入中…";const {data,error}=await db.auth.signInWithPassword({email:$("loginEmail").value,password:$("loginPassword").value});$("loginMsg").textContent=error?error.message:"";if(data.user)showApp(data.user)}
$("logoutBtn").onclick=async()=>{await db.auth.signOut();location.reload()}
function showApp(u){$("login").hidden=true;$("app").hidden=false;$("userEmail").textContent=u.email;loadAll()}
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(t=>t.hidden=true);$(b.dataset.tab).hidden=false;document.querySelectorAll("[data-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("pageTitle").textContent=b.textContent})
async function upload(file,folder){if(!file)return"";const ext=file.name.split(".").pop();const path=`${folder}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from("website-media").upload(path,file,{upsert:false});if(error)throw error;return db.storage.from("website-media").getPublicUrl(path).data.publicUrl}
async function loadAll(){await Promise.all([loadAbout(),loadServices(),loadMaterials(),loadProjects(),loadDM(),loadContact()]);fillSelects()}
async function loadAbout(){const {data}=await db.from("about_content").select("*").eq("id",1).maybeSingle();if(!data)return;$("aTitle").value=data.title||"";$("aSummary").value=data.summary||"";$("aContent").value=data.content||"";$("aPhilosophy").value=data.philosophy||""}
$("aboutForm").onsubmit=async e=>{e.preventDefault();const {error}=await db.from("about_content").update({title:$("aTitle").value,summary:$("aSummary").value,content:$("aContent").value,philosophy:$("aPhilosophy").value,updated_at:new Date().toISOString()}).eq("id",1);$("aboutMsg").textContent=error?error.message:"✓ 已儲存"}
async function loadServices(){const {data}=await db.from("services").select("*").order("sort_order");services=data||[];$("serviceList").innerHTML=services.map(x=>`<div class="list-item"><div><b>${x.name}</b><br><small>${x.active?"官網顯示":"已隱藏"}</small></div><div class="actions"><button onclick="editService('${x.id}')">編輯</button><button class="delete" onclick="delService('${x.id}')">刪除</button></div></div>`).join("");fillSelects()}
$("serviceForm").onsubmit=async e=>{e.preventDefault();try{let image="";if($("sImage").files[0])image=await upload($("sImage").files[0],"services");let payload={name:$("sName").value,description:$("sDesc").value,full_content:$("sFull").value,applications:$("sApps").value,sort_order:+$("sOrder").value||0,active:$("sActive").checked};if(image)payload.image_url=image;let q=$("sId").value?db.from("services").update(payload).eq("id",$("sId").value):db.from("services").insert(payload);let {error}=await q;if(error)throw error;resetService();await loadServices()}catch(err){alert(err.message)}}
window.editService=id=>{let x=services.find(v=>v.id===id);$("sId").value=x.id;$("sName").value=x.name;$("sDesc").value=x.description||"";$("sFull").value=x.full_content||"";$("sApps").value=x.applications||"";$("sOrder").value=x.sort_order||0;$("sActive").checked=x.active;scrollTo({top:0,behavior:"smooth"})}
window.delService=async id=>{if(confirm("確定刪除此服務？")){await db.from("services").delete().eq("id",id);loadServices()}}
function resetService(){$("serviceForm").reset();$("sId").value="";$("sActive").checked=true}$("sReset").onclick=resetService
async function loadMaterials(){const {data}=await db.from("materials").select("*").order("category").order("sort_order");materials=data||[];$("materialList").innerHTML=materials.map(x=>`<div class="list-item"><div><b>${x.name}</b> <small>${x.category}｜${x.active?"顯示":"隱藏"}</small></div><div class="actions"><button onclick="editMaterial('${x.id}')">編輯</button><button class="delete" onclick="delMaterial('${x.id}')">刪除</button></div></div>`).join("");fillSelects()}
$("materialForm").onsubmit=async e=>{e.preventDefault();try{let image="";if($("mImage").files[0])image=await upload($("mImage").files[0],"materials");let p={category:$("mCategory").value,name:$("mName").value,summary:$("mSummary").value,full_content:$("mFull").value,features:$("mFeatures").value,applications:$("mApps").value,cautions:$("mCautions").value,strength:+$("mStrength").value,toughness:+$("mToughness").value,heat_resistance:+$("mHeat").value,surface_quality:+$("mSurface").value,sort_order:+$("mOrder").value||0,active:$("mActive").checked};if(image)p.image_url=image;let q=$("mId").value?db.from("materials").update(p).eq("id",$("mId").value):db.from("materials").insert(p);let {error}=await q;if(error)throw error;resetMaterial();await loadMaterials()}catch(err){alert(err.message)}}
window.editMaterial=id=>{let x=materials.find(v=>v.id===id);$("mId").value=x.id;$("mCategory").value=x.category;$("mName").value=x.name;$("mSummary").value=x.summary||"";$("mFull").value=x.full_content||"";$("mFeatures").value=x.features||"";$("mApps").value=x.applications||"";$("mCautions").value=x.cautions||"";$("mStrength").value=x.strength||3;$("mToughness").value=x.toughness||3;$("mHeat").value=x.heat_resistance||3;$("mSurface").value=x.surface_quality||3;$("mOrder").value=x.sort_order||0;$("mActive").checked=x.active;scrollTo({top:0,behavior:"smooth"})}
window.delMaterial=async id=>{if(confirm("確定刪除此材料？")){await db.from("materials").delete().eq("id",id);loadMaterials()}}
function resetMaterial(){$("materialForm").reset();$("mId").value="";["mStrength","mToughness","mHeat","mSurface"].forEach(x=>$(x).value=3);$("mActive").checked=true}$("mReset").onclick=resetMaterial
function fillSelects(){if(!$("pService"))return;$("pService").innerHTML='<option value="">未指定</option>'+services.map(x=>`<option value="${x.id}">${x.name}</option>`).join("");$("pMaterial").innerHTML='<option value="">未指定</option>'+materials.map(x=>`<option value="${x.id}">${x.name}</option>`).join("")}
async function loadProjects(){const {data}=await db.from("projects").select("*").order("sort_order");projects=data||[];$("projectList").innerHTML=projects.map(x=>`<div class="list-item"><div><b>${x.title}</b><br><small>${x.published?"已發布":"草稿"}${x.featured?"｜精選":""}</small></div><div class="actions"><button onclick="editProject('${x.id}')">編輯</button><button class="delete" onclick="delProject('${x.id}')">刪除</button></div></div>`).join("")}
$("projectForm").onsubmit=async e=>{e.preventDefault();try{let cover="";if($("pCover").files[0])cover=await upload($("pCover").files[0],"projects");let gallery=[];for(const f of $("pGallery").files)gallery.push(await upload(f,"projects/gallery"));let old=projects.find(x=>x.id===$("pId").value);let p={title:$("pTitle").value,client_name:$("pClient").value,hide_client:$("pHideClient").checked,service_id:$("pService").value||null,material_id:$("pMaterial").value||null,summary:$("pSummary").value,content:$("pContent").value,featured:$("pFeatured").checked,published:$("pPublished").checked,sort_order:+$("pOrder").value||0};if(cover)p.cover_url=cover;if(gallery.length)p.gallery_urls=[...(old?.gallery_urls||[]),...gallery];let q=$("pId").value?db.from("projects").update(p).eq("id",$("pId").value):db.from("projects").insert(p);let {error}=await q;if(error)throw error;resetProject();await loadProjects()}catch(err){alert(err.message)}}
window.editProject=id=>{let x=projects.find(v=>v.id===id);$("pId").value=x.id;$("pTitle").value=x.title;$("pClient").value=x.client_name||"";$("pHideClient").checked=x.hide_client;$("pService").value=x.service_id||"";$("pMaterial").value=x.material_id||"";$("pSummary").value=x.summary||"";$("pContent").value=x.content||"";$("pFeatured").checked=x.featured;$("pPublished").checked=x.published;$("pOrder").value=x.sort_order||0;scrollTo({top:0,behavior:"smooth"})}
window.delProject=async id=>{if(confirm("確定刪除此案例？")){await db.from("projects").delete().eq("id",id);loadProjects()}}
function resetProject(){$("projectForm").reset();$("pId").value="";$("pHideClient").checked=true;$("pPublished").checked=true;fillSelects()}$("pReset").onclick=resetProject
async function loadDM(){const {data}=await db.from("dm_files").select("*").eq("id",1).maybeSingle();if(data)$("dmTitle").value=data.title||""}
$("dmForm").onsubmit=async e=>{e.preventDefault();try{let p={title:$("dmTitle").value,updated_at:new Date().toISOString()};if($("dmFile").files[0])p.file_url=await upload($("dmFile").files[0],"dm");let {error}=await db.from("dm_files").update(p).eq("id",1);if(error)throw error;$("dmMsg").textContent="✓ DM 已更新"}catch(err){$("dmMsg").textContent=err.message}}
async function loadContact(){const {data}=await db.from("site_settings").select("*").eq("id",1).maybeSingle();if(!data)return;$("cEmail").value=data.email||"";$("cLine").value=data.line_url||"";$("cPhone").value=data.phone||"";$("cInstagram").value=data.instagram_url||"";$("cFacebook").value=data.facebook_url||"";$("cAddress").value=data.address||"";$("showEmail").checked=data.show_email;$("showLine").checked=data.show_line;$("showPhone").checked=data.show_phone;$("showInstagram").checked=data.show_instagram;$("showFacebook").checked=data.show_facebook;$("showAddress").checked=data.show_address}
$("contactForm").onsubmit=async e=>{e.preventDefault();let p={email:$("cEmail").value,line_url:$("cLine").value,phone:$("cPhone").value,instagram_url:$("cInstagram").value,facebook_url:$("cFacebook").value,address:$("cAddress").value,show_email:$("showEmail").checked,show_line:$("showLine").checked,show_phone:$("showPhone").checked,show_instagram:$("showInstagram").checked,show_facebook:$("showFacebook").checked,show_address:$("showAddress").checked,updated_at:new Date().toISOString()};let {error}=await db.from("site_settings").update(p).eq("id",1);$("contactMsg").textContent=error?error.message:"✓ 已儲存"}
boot();
